### ISSUE TITLE
Snapping videos to top lesson error

### ISSUE THREAD

**Issue by EncryptedUser7** [codedamn/core#9]
When doing the Snapping videos to top playground from the react course's tik tok app, when I run my program, I get the following message:
```
Running your code now. Please wait[running] Stdout: yarn run v1.22.11
$ (jest --runInBand --json --outputFile=payload.json || true) && node validator.js
Done in 3.12s.
[running] Stderr: warning package.json: No license field
FAIL ./main.test.js
  ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

      39 |              args: [
      40 |                      '--no-sandbox',
    > 41 |                      '--disable-setuid-sandbox',
         |                                                 ^
      42 |                      '--disable-dev-shm-usage',
      43 |                      '--disable-accelerated-2d-canvas',
      44 |                      '--no-first-run',

      at _run (main.test.js:41:42)
      at run (main.test.js:37:15)
      at Object.<anonymous> (main.test.js:159:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.232 s
Ran all test suites.
Test results written to: payload.json

```

I'm pretty sure this is on Codedamn's end as I never touched anything other than the files in the src directory.  In addition, it is failing to recognize that I have successfully made it so that the videos snap to the screen correctly

**Comment by mehulmpt** [comment]
Thanks for reporting. @Pranavtechie can you take a look?

**Comment by Pranavtechie** [comment]
Hey @EncryptedUser7 sorry for the delayed reply, this issue has been resolved the test cases have been fixed. You can complete the excerise labs right now.
